language: php

php:
    - '5.6'
    - '7.1'
    - '7.2'
    - '7.3'

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

branches:
    only:
        - master

env:
    matrix:
        - PREFER_LOWEST="--prefer-lowest"
        - PREFER_LOWEST=""

install:
    - composer update $PREFER_LOWEST

script:
    - composer test
