language: php

cache:
    directories:
        - $HOME/.composer/cache

branches:
    only:
        - master

matrix:
    include:
        - php: 5.6
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 7.2
          env: CODECEPT_VERSION="^3.0"
        - php: 7.2
          env: CODECEPT_VERSION="^4.0"
        - php: 7.3
          env: CODECEPT_VERSION="^3.0"
        - php: 7.3
          env: CODECEPT_VERSION="^4.0"
        - php: 7.4
          env: CODECEPT_VERSION="^4.0"
        - php: 8.0
        - php: 8.1

before_install:
    - if [ "$CODECEPT_VERSION" != "" ]; then composer require --dev --no-update codeception/codeception:"$CODECEPT_VERSION"; fi

install:
    - composer update $COMPOSER_FLAGS

script:
    - composer test
