name: Run Tests

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    run-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version:
                    - 8.0
                    - 8.1
                codeception-version:
                    - ^4.0
                    - ^5.0
        steps:
            -   uses: actions/checkout@v3

            -   name: Setup PHP ${{ matrix.php-version }}
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}

            -   name: Setup Codeception ${{ matrix.codeception-version }}
                run: composer require --dev --no-update codeception/codeception:${{ matrix.codeception-version }}

            -   name: Install Dependencies
                run: composer update

            -   name: Run Tests
                run: composer test
